@host = localhost
@port = 5050

###? Alta de usuarios
### Register
POST http://{{host}}:{{port}}/api/usuarios/register/
Content-Type: application/json

{
  "nombre": "Pablo Berdasco",
  "mail": "p.berdasco@gmail.com",
  "password": "1234"
}

###? =====================================================================
###? LOGIN desde un navegador  (usa tokens en Cookies httpOnly + sameSite)
### Nota: rest client si guarda el cookie, en general en c:\users\yo\.rest-client\cookie.json
### Login OK
# @no-cookie-jar
POST http://{{host}}:{{port}}/api/usuarios/login/
Content-Type: application/json

{
  "mail": "p.berdasco@gmail.com",
  "password": "1234"
}

###! Login Fail - Credentials 1
POST http://{{host}}:{{port}}/api/usuarios/login/
Content-Type: application/json

{
  "mail": "p.berdasco@gmail.com",
  "password": "2222"
}

###! Login Fail - Credentials 2
POST http://{{host}}:{{port}}/api/usuarios/login/
Content-Type: application/json

{
  "mail": "pberdasco@gmail.com",
  "password": "1234"
}

###! Login Fail - Bad Request
POST http://{{host}}:{{port}}/api/usuarios/login/
Content-Type: application/json

{
  "mail": "p.berdasco@gmail.com"
}

### Get Roles & Derechos con cookies (desde navegador o cliente con cookie jar)
GET http://{{host}}:{{port}}/api/usuarios/me

### Logout con cookies (desde navegador o cliente con cookie jar)
POST http://{{host}}:{{port}}/api/usuarios/logout


###? ==================================================================
###? LOGIN desde aplicaciones usa JWT para incluir en Bearer

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibm9tYnJlIjoiUGFibG8gQmVyZGFzY28iLCJtYWlsIjoicC5iZXJkYXNjb0BnbWFpbC5jb20iLCJpYXQiOjE3NTQxODY3NDEsImV4cCI6MTc1NDE5Mzk0MX0.u4v_2HTjj464XHTtDDA4e608BLCyBCTyZoKc3cFVHlQ
@refreshToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibm9tYnJlIjoiUGFibG8gQmVyZGFzY28iLCJtYWlsIjoicC5iZXJkYXNjb0BnbWFpbC5jb20iLCJpYXQiOjE3NTQxODY2NjcsImV4cCI6MTc1NDc5MTQ2N30.bZp_yh_qLoBpBpX_hz1pSw-cJYSCoT4d2xYB_TWnOws

### Login Ok
POST http://{{host}}:{{port}}/api/usuarios/api-token/
Content-Type: application/json

{
  "mail": "p.berdasco@gmail.com",
  "password": "1234"
}

###! Get Roles & Derechos - con falla por falta de bearer
GET http://{{host}}:{{port}}/api/usuarios/me


### Get Roles & Derechos - Ok 
GET http://{{host}}:{{port}}/api/usuarios/me
Authorization: Bearer {{token}}


### Refresh con Bearer 
POST http://{{host}}:{{port}}/api/usuarios/refresh
Authorization: Bearer {{refreshToken}}

### LogOut
POST http://{{host}}:{{port}}/api/usuarios/logout
Authorization: Bearer {{token}}